### ISSUE TITLE
Encourage making mixin classes abstract

### ISSUE THREAD

**Issue by i509VCB** [LeoCTH/tips-and-tricks#1]
I believe the advice around the community is to keep your mixins abstract for a few reasons:

- less spammy shadowing, no need to throw inside those methods
- makes the class not instantiable without extension. Since you can't just plainly instantiate it discourages that. Mixin will always refuse to load the class if it is a mixin of course.

**Comment by pluiedev** [comment]
Actually I think this deserves a separate article

**Comment by pluiedev** [comment]
There we go. Mixins should always be abstract. :> https://github.com/LeoCTH/tips-and-tricks/blob/main/minecraft-modding/mixins/mixins-should-always-be-abstract.md
